








version: '2'

services:
    haproxy2:
        image: haproxy:1.7
        ports:
            # stats
            - "8036:8036"

            # splash
            - "8050:8050"
        links:
            - splashu0
            - splashu1
            - splashu2

        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
            - ./filters:/etc/splash/filters:ro

    splashu0:
        image: scrapinghub/splash:3.4.1
        command: --max-timeout 20 --slots 20 --maxrss 628 --verbosity 0 --browser-engines=webkit
        expose:
            - 8050
        mem_limit: 816m
        memswap_limit: 1012m
        restart: always
        volumes:
            - ./filters:/etc/splash/filters:ro

    splashu1:
        image: scrapinghub/splash:3.4.1
        command: --max-timeout 20 --slots 20 --maxrss 628 --verbosity 0 --browser-engines=webkit
        expose:
            - 8050
        mem_limit: 816m
        memswap_limit: 1012m
        restart: always
        volumes:
            - ./filters:/etc/splash/filters:ro

    splashu2:
        image: scrapinghub/splash:3.4.1
        command: --max-timeout 20 --slots 20 --maxrss 628 --verbosity 0 --browser-engines=webkit
        expose:
            - 8050
        mem_limit: 816m
        memswap_limit: 1012m
        restart: always
        volumes:
            - ./filters:/etc/splash/filters:ro

